# Python for Data Science

## Numpy practice

In [2]:
import numpy as np

# 1. Introductory numpy exercises

Use vectorization (like A+A which is the item-by-item addition) instead of for cycles. You need to implement a function in each excersise which has a NumPy array as its input.

## 1.1 Standardization for 2D arrays.

\begin{equation*}
X_{std} = \frac{X - \mu}{\sigma},
\end{equation*}

Where $\mu$ is the mean and $\sigma$ is the standard deviation.

## 1.2 Normalization of 2D arrays.

\begin{equation*}
X_{norm} = \frac{X - X_{min}}{X_{max} - X_{min}}
\end{equation*}

## 1.3 Create the softmax function.
$$
x_i \mapsto \frac{\exp(x_i)}{\sum_{j=1}^n \exp(x_j)}
$$

# 2. Vectorization

Transform the examples below into vectorized form (without for cycles and lists).

## 2.1 Euclidean norm line by line

Create a function which computes the Euclidean norm of each line for a 2D array. Use `numpy` operations and vectorization, avoid `for` cycles. Here is the *wrong* solution.

In [2]:
def rowwise_norm(X):
    def my_dot(x, y):
        result = 0.0
        for i in range(len(x)):
            result += x[i] * y[i]
        return result
    return np.array([np.sqrt(my_dot(x, x)) for x in X])

X = np.arange(5)[:, None]*np.ones((5, 3));
print(X)
print(rowwise_norm(X))
print(rowwise_norm([[1], [-1], [1], [-1]]))

[[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]
 [4. 4. 4.]]
[0.         1.73205081 3.46410162 5.19615242 6.92820323]
[1. 1. 1. 1.]


## 2.2 Chessboard

Create a function which produces an $n\times n$ array which contains $\pm1$ numbers like a chessboard. $\left(M_{i,j} = (-1)^{i+j}\right)$

In [ ]:
def chessboard(n):

chessboard(5)

# 3. Broadcast quiz

Will the operations below work, and if so, what will be the shape of the result?
* Try to think of the result first without running the cells below.

In [3]:
np.ones(3) + np.ones((3,3))

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [4]:
np.ones(3) + np.ones((4, 3))

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [5]:
np.ones(3) + np.ones((3, 4))

ValueError: operands could not be broadcast together with shapes (3,) (3,4) 

In [6]:
np.ones(3)[:, None] + np.ones((3, 4))

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [7]:
np.ones((1, 2, 3)) + np.ones((1, 3))[:, None, :]

array([[[2., 2., 2.],
        [2., 2., 2.]]])

In [8]:
np.ones((1, 2, 3)) + np.ones((1, 3))

array([[[2., 2., 2.],
        [2., 2., 2.]]])

# 4. Advanced NumPy exercises

## 4.1 Block-matrix

Create a function called __`blockmatrix`__ , which will generate the following square matrix:

$$
\left(\begin{array}{ccc|ccc}
 1 & & 0& 0 & \cdots & 0 \\
 & \ddots & & \vdots & & \vdots \\
  0& & 1 & 0 & \cdots & 0 \\\hline
  0 & \cdots & 0 & 1 & \cdots & 1 \\
  \vdots & & \vdots & \vdots & & \vdots \\
  0 & \cdots & 0 & 1 & \cdots & 1
\end{array}\right)
$$

The upper left block is an identity matrix, the lower right block is a square matrix consisting of all $1$s, the rest two blocks are all $0$ matrices. The function should expect two positive integers as an input, the first needs to specify the size of the upper right identity matrix, and the second should specify the lower right $1$ matrix's size.
You can use the NumPy generators `ones`, `zeros`, `eye` and concatenation only.

## 4.2 Block-matrix from any square matrices

Create a function which expects any number of square matrices and outputs a block-matrix which contains the input matrices in its main diagonal, and contains 0 in every other place.

## 4.3 Numeric derivative

Create a __`derivate`__ function estimates the derivate of an $\mathbb{R}\mapsto\mathbb{R}$ function numerically using the finite difference method. Implement the function using NumPy, without for cycles!

The input is a one-dimensional `f np.array` containing the function's values and an optional one-dimensional `x np.array` containing the x values. If the user does not define `x` , it should have a default value of `x =  [0, 1, ..., n]`.  

Output is a one-dimensional `f np.array` of which length is one less than the input array's lenght.